name: Java CI

on:
  push:
    branches:
      - actions
      - $default-branch
      - $protected-branches
  pull_request:
    branches:
      - actions
      - $default-branch
  release:
    types: [created]
  workflow_dispatch:

jobs:
  call-workflow:
    uses: JOSM/JOSMPluginAction/.github/workflows/ant.yml@main

